hint_texts = [
    "Did you know that if you spam left and right on a checkpoint, you get more jumps?",
    "Don't name yourself JimmyQrg, I dare you.",
    "I hate the 5 Pantheon. What? I'm not in Hollow Knight? Ah..",
    "If you set the spike touchbox to Tip Spike, you can walk through them. Don't fall on them though.",
    "Press R to activate the rotate tool. Click and drag to spin objects!",
    "Teleportals only work when both ends are connected. Check your Send To and Receive From settings!",
    "You can flip objects horizontally in the config panel. Great for symmetrical designs!",
    "The eraser tool (Q) can have custom width and height. Big eraser = big destruction.",
    "Custom backgrounds can really set the mood. Try uploading your own!",
    "Drop Hurt Only spikes are perfect for one-way passages.",
    "Zones are invisible during gameplay. Use them for kill zones or special effects!",
    "You can adjust the font size in settings. Squint no more!",
    "The inspect box in test mode shows all object properties. Debug like a pro!",
    "Music keeps playing between editor and test mode. Vibe while you build!",
    "Ctrl+Scroll to zoom in editor mode. Ctrl+Shift+Scroll to reset zoom.",
    "Text objects pass right through players. Use them for signs and decorations!",
    "The loading screen has hints. Oh wait, you're reading one right now...",
    "Hosting a game? Share the room code with friends to play together!",
    "Your player color is unique to your account. Stand out in multiplayer!",
    "Export your map as a .pkrn file to share with others.",
    "Import maps from files to play community creations!",
    "Gravity can be adjusted in config. Try negative gravity for ceiling runners!",
    "Jump height and movement speed are customizable per map.",
    "Additional airjump lets you jump even when not touching the ground.",
    "Touch controls include a virtual joystick. Great for mobile play!",
    "As the host, you can kick players who aren't playing nice.",
    "Your best times are displayed when you complete a level. Speed run!",
    "Layers help organize complex maps. Use them wisely!",
    "Custom music supports MP3 files. Add your favorite tunes!",
    "Invalid teleportal connections appear red. Fix them to enable teleportation!",
    "Fly mode in test mode lets you explore without restrictions.",
    "Ground jumps vs air jumps matter when additional airjump is disabled.",
    "Spikes have adjustable touchboxes. Flat, Danger, or Tip - choose wisely!",
    "Portal colors can be customized. Color-code your teleport network!",
    "This game was made with love, caffeine, and questionable sleep schedules.",
    "Sometimes the best parkour is knowing when NOT to jump.",
    "Every great map starts with a terrible first draft.",
    "If you're stuck, try looking at the problem from a different angle. Literally.",
    "The best speedrunners know every pixel. Do you?",
    "Fun fact: The developer tested this loading screen way too many times.",
    "Remember: Frustration is just delayed satisfaction.",
    "Pro tip: Blame the spikes, not yourself.",
    "Have you tried turning the gravity off and on again?",
    "Your map could be someone's favorite. Keep building!",
    "The finish line is just the beginning of another run."
]
